version: '3.4'

services:
  chat.api:
    build: .
    ports:
      - '7043:80'
    environment:
      CONNECTION_STRING_DOCKER: "host=db;Database=messagedb;Port=5432;Username=postgres;Password=admin"
    networks:
      - chatapp
    depends_on:
      - rabbitmq

  react:
    build: ./Chat.Api/Clientapp
    ports:
      - '3000:3000'
    networks:
      - chatapp
  
  db:
    image: postgres:latest
    ports:
      - '5432:5433'
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "messagedb"
    networks:
      - chatapp
    
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - chatapp
networks:
  chatapp:
    driver: bridge