version: '3.4'

services:
  chat.api:
    image: ${DOCKER_REGISTRY-}chatapi
    build:
      context: .
      dockerfile: /Dockerfile
    ports:
        - '7047:443'
        - '7048:80'     
    depends_on:
      - "rabbitmq"

  rabbitmq:
    container_name: "rabbitmqcontainer"
    image: rabbitmq:management
    hostname: "rabbitmq"
    ports:
        - '5672:5672'
        - '15672:15672'
#  react:
#    container_name: react
#    build:
#      context: .
#      dockerfile: Clientapp/Dockerfile
#    volumes:
#      - '.:/app'
#      - '/app/node_modules'
#    ports:
#      - "3001:3000"
#    environment:
#      - CHOKIDAR_USEPOLLING=true
#    depends_on:
#      - "rabbitmq"